backend:
  name: github
  repo: remichauvinproduction-web/siteweb
  branch: main
  base_url: https://oauth-proxy.remiproduction.workers.dev
  auth_endpoint: oauth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        name: "home"
        label: "Accueil"
        fields:
          - { name: "body", label: "Contenu", widget: "markdown" }
